version: '3.9'

# servicos
services:
  instadev:
    image: 'postgres:latest'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: He32206672+
      POSTGRES_DB: bd-instadev
    volumes:
      - ./data:/var/lib/postgresql